### ISSUE TITLE
Add wikidata image link

### ISSUE THREAD

**Issue by pasqLisena** [Odeuropa/vocabularies#3]
When interlinked to wikidata, add the image link

**Comment by pasqLisena** [comment]
Notify https://github.com/Odeuropa/explorer/issues/34 when done

**Comment by ehrhart** [comment]
It looks like the image link is represented as a string instead of an URI, and with http://schema.org instead of https://schema.org like the other properites in the model. Is this something that can be changed?

Example: http://data.odeuropa.eu/vocabulary/olfactory-objects/198

**Comment by rtroncy** [comment]
This is indeed a bug that should be changed
